name: Deploy RxJS Conf site
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RXJS_CONF_HOST }}
        username: ${{ secrets.RXJS_CONF_USER }}
        key: ${{ secrets.RXJS_CONF_DEPLOY_PRIVATE_SSH }}
        script: "curl https://raw.githubusercontent.com/learnrxjs/rxjsconf/master/misc/start.sh | bash"
